# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  matrix:
  - R_VERSION: stable
    R_ARCH: x64
    BIOC_USE_DEVEL: FALSE
    PKGTYPE: both

branches:
  only:
    - main

build_script:
  - Rscript -e install.packages('openssl',type='binary',repos='https://cran.rstudio.com')
  - Rscript -e install.packages('ragg',type='binary',repos='https://cran.rstudio.com')
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps
  - travis-tool.sh install_github xihaoli/STAAR
  - travis-tool.sh install_github zilinli1988/SCANG

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs
