on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
      - name: Install RSQLite
        run: |
          install.packages("RSQLite")
        shell: Rscript {0}
      - name: Install BiocManager
        run: |
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
        shell: Rscript {0}
      - name: Install GenomicFeatures, TxDb.Hsapiens.UCSC.hg38.knownGene, GENESIS
        run: |
          BiocManager::install(c("GenomicFeatures", "TxDb.Hsapiens.UCSC.hg38.knownGene", "GENESIS"))
        shell: Rscript {0}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github(c("xihaoli/STAAR", "xihaoli/MultiSTAAR", "zilinli1988/SCANG"))
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
